
[google]
client_id     = "YOUR_GOOGLE_CLIENT_ID"
client_secret = "YOUR_GOOGLE_CLIENT_SECRET"
redirect_uri  = "https://your-app.streamlit.app"  # must match OAuth client
# Choose the least privilege you can. 'drive.file' limits to files created/opened via your app.
# Use 'drive' if you need to list/update arbitrary files in your Drive.
scopes        = ["https://www.googleapis.com/auth/drive"]
