
[google]
client_id     = "YOUR_CLIENT_ID.apps.googleusercontent.com"
client_secret = "YOUR_CLIENT_SECRET"
redirect_uri  = "https://your-app.streamlit.app"
scopes        = ["https://www.googleapis.com/auth/drive.file"]
api_key       = "YOUR_RESTRICTED_API_KEY"
app_id        = "YOUR_PROJECT_NUMBER"
